name: Scrape All Teams

on:
  schedule:
    - cron: '0 9 * * *'  # 毎日18:00 JST
  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run All Team Scraper
        run: python scrape_all_teams.py
