name: Scrape All Teams

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4
          playwright install

      - name: Run scraper
        run: python scrape_all_teams.py

      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: ryukyu-screenshot
          path: screenshot.png
